# Generated by Django 2.1.3 on 2020-04-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
